# -*- coding: utf-8 -*-
"""Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1synUQyWMRJ6lkqDHnHxmweOaD6sLooVR
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()
df = pd.read_csv('merged_data.csv')

print("First five rows of dataset: ")
print(df.head())

print("\nDataFrame summary:")
print(df.info())

print(df.isnull())

duplicates = df.duplicated()
print("Duplicate row:\n", duplicates)